INSERT INTO LANGUAGES (LANGUAGE) VALUES ('English');
INSERT INTO LANGUAGES (LANGUAGE) VALUES ('Spanish');
INSERT INTO WORDS (WORD) VALUES ('Hello');
INSERT INTO WORDS (WORD) VALUES ('People');
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Gente', (SELECT WORD_ID FROM WORDS WHERE WORD = 'People'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'Spanish'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Hola', (SELECT WORD_ID FROM WORDS WHERE WORD = 'Hello'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'Spanish'));



